version: '2.1'

services:
  masternode:
    image: bizancio.core:latest
    build: .
    ports:
      - 3001:5556
      - 4000:5001
    # environment:
    #   - MASTER=TRUE
  # node1:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3002:5556
  #     - 4001:5001
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "masternode"
  # node2:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3003:5556
  #     - 4002:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node1"
  # node3:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3004:5556
  #     - 4003:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node2"
  # node4:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3005:5556
  #     - 4004:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node3"

  # node5:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3006:5556
  #     - 4005:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node4"
  # node6:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3007:5556
  #     - 4006:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node5"
  # node7:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3008:5556
  #     - 4007:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node6"
  # node8:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3009:5556
  #     - 4008:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node7"
  # node9:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3010:5556
  #     - 4009:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node8"
  # node10:
  #   image: bizancio.core:latest
  #   ports:
  #     - 3010:5556
  #     - 4010:5000
  #   environment:
  #     - MASTER=FALSE
  #   depends_on:
  #     - "node9"
      